name: Documentation Deployment

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - '*.md'
      - 'package.json'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build documentation
      run: |
        echo "Building documentation..."
        mkdir -p public/docs
        # Simulate documentation build process
        find . -name "*.md" -exec cp {} public/docs/ \; || echo "No markdown files found"
        echo "# Project Documentation" > public/docs/index.md
        echo "Built on: $(date)" >> public/docs/index.md
        echo "Documentation build completed"
    
    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: public/docs/

  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-docs
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download documentation
      uses: actions/download-artifact@v4
      with:
        name: documentation
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public/docs
        force_orphan: true
    
    - name: Documentation deployment status
      run: echo "Documentation deployed successfully at $(date)"